export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;
export const REFRESH_TOKEN_TTL_SECONDS = 24 * 60 * 60;
export const REFRESH_TOKEN_REMEMBER_TTL_SECONDS = 30 * 24 * 60 * 60;

export const BCRYPT_ROUNDS = 12;

export const LOGIN_MAX_ATTEMPTS = 7;
export const LOGIN_LOCKOUT_SECONDS = 3 * 60;

export const CSRF_COOKIE_NAME = 'torbook_csrf';
export const REFRESH_COOKIE_NAME = 'torbook_refresh';

export const API_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  INVALID_CSRF: 'INVALID_CSRF',
  SLOT_TAKEN: 'SLOT_TAKEN',
  PAST_APPOINTMENT: 'PAST_APPOINTMENT',
  FUTURE_APPOINTMENTS_EXIST: 'FUTURE_APPOINTMENTS_EXIST',
  SERVICE_HAS_APPOINTMENTS: 'SERVICE_HAS_APPOINTMENTS',
  EMPLOYEE_LIMIT_REACHED: 'EMPLOYEE_LIMIT_REACHED',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  ACCOUNT_EXISTS_LOCAL: 'ACCOUNT_EXISTS_LOCAL',
  GOOGLE_ACCOUNT_NOT_FOUND: 'GOOGLE_ACCOUNT_NOT_FOUND',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLE_HAS_EMPLOYEES: 'ROLE_HAS_EMPLOYEES',
  ROLE_LIMIT_REACHED: 'ROLE_LIMIT_REACHED',
} as const;

export const MAX_EMPLOYEES_PER_BUSINESS = 5;
export const MAX_EMPLOYEE_ROLES_PER_BUSINESS = 10;
export const EMPLOYEE_INVITE_TTL_DAYS = 7;

export const SLOT_CACHE_TTL_SECONDS = 30;

export const BUSINESS_CATEGORIES = [
  'יופי וטיפוח',
  'ספרות',
  'כושר ובריאות',
  'רפואה',
  'פיננסים',
  'ייעוץ',
  'בייביסיטר',
  'אחר',
] as const;
