export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;
export const REFRESH_TOKEN_TTL_SECONDS = 24 * 60 * 60;
export const REFRESH_TOKEN_REMEMBER_TTL_SECONDS = 30 * 24 * 60 * 60;

export const BCRYPT_ROUNDS = 12;

export const LOGIN_MAX_ATTEMPTS = 5;
export const LOGIN_LOCKOUT_SECONDS = 15 * 60;

export const CSRF_COOKIE_NAME = 'torbook_csrf';
export const REFRESH_COOKIE_NAME = 'torbook_refresh';

export const API_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  INVALID_CSRF: 'INVALID_CSRF',
  SLOT_TAKEN: 'SLOT_TAKEN',
  PAST_APPOINTMENT: 'PAST_APPOINTMENT',
  FUTURE_APPOINTMENTS_EXIST: 'FUTURE_APPOINTMENTS_EXIST',
  SERVICE_HAS_APPOINTMENTS: 'SERVICE_HAS_APPOINTMENTS',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
} as const;

export const SLOT_CACHE_TTL_SECONDS = 30;
