export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum AuthProvider {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_BUSINESS = 'CANCELLED_BY_BUSINESS',
  COMPLETED = 'COMPLETED',
  PENDING_OWNER_DECISION = 'PENDING_OWNER_DECISION',
}

export enum CommentSentiment {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  NEUTRAL = 'NEUTRAL',
}

export enum EmployeePermission {
  VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS',
  CANCEL_APPOINTMENTS = 'CANCEL_APPOINTMENTS',
  BROADCAST_MESSAGE = 'BROADCAST_MESSAGE',
  EDIT_BUSINESS_MEDIA = 'EDIT_BUSINESS_MEDIA',
  EDIT_BUSINESS_SOCIAL = 'EDIT_BUSINESS_SOCIAL',
  EDIT_BUSINESS_PROFILE = 'EDIT_BUSINESS_PROFILE',
  EDIT_BUSINESS_SCHEDULE = 'EDIT_BUSINESS_SCHEDULE',
  MANAGE_SERVICES = 'MANAGE_SERVICES',
  EDIT_CANCELLATION_POLICY = 'EDIT_CANCELLATION_POLICY',
}
