export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
}

export enum AuthProvider {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_BUSINESS = 'CANCELLED_BY_BUSINESS',
  COMPLETED = 'COMPLETED',
  PENDING_OWNER_DECISION = 'PENDING_OWNER_DECISION',
}
